import { Box, Heading, Text } from "@chakra-ui/react";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import Head from "next/head";
import MainPage from "../components/MainPage";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <div>
      <Head>
        <title>Coop Loan App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box>
        {!session ? (
          <>
            <Box pt='20' px='6' maxW='2xl' mx='auto'>
              <Heading
                bgGradient='linear(to-r, green.500, pink, white)'
                bgClip='text'>
                COOPLoan
              </Heading>
              <Text
                maxW='xs'
                mx='auto'
                mt='6'
                color='gray'
                fontWeight='semibold'
                fontSize='2xl'>
                Sign in / Sign up
              </Text>
              <Box maxW='xs' mx='auto'>
                <Auth
                  // providers={["google", "facebook"]}
                  // socialLayout='horizontal'
                  supabaseClient={supabase}
                  appearance={{ theme: ThemeSupa }}
                  theme='dark'
                />
              </Box>
            </Box>
          </>
        ) : (
          // <Account session={session} />
          <MainPage session={session} />
        )}
      </Box>
    </div>
  );
}
